created entities and added constraints
blerinebee/todo-app-backend pull request #1
Opened 2022-12-06 18:50 UTC by shawn-lacarta

2022-12-11 15:17 UTC, Milena-Blaser commented on src/main/java/m426/todoapp/todoappbe/auth/Auth.java
>  public class Auth {
Ich würde es Authority nennen

2022-12-11 15:23 UTC, Milena-Blaser requested changes
Bei Task fehlt die todolist id und in ToDolist wird Task task entweder nicht gebraucht oder sollte ein Set sein

2022-12-12 16:52 UTC, blerineberisha commented on src/main/java/m426/todoapp/todoappbe/authorities/Authorities.java
> +public class Authorities {
Sollte Singular sein

2022-12-12 16:54 UTC, blerineberisha requested changes
Alles gut, aber zuerst noch kurz Authorities zu Authority abändern, dann kann gemerged werden. 👍🏻

2022-12-12 17:31 UTC, alishakhalid commented on src/main/java/m426/todoapp/todoappbe/authorities/Authorities.java
> +import jakarta.persistence.*;
Dieser import statement sollte überall geändert werden zu:
import javax.persistence.*;

2022-12-12 19:24 UTC, Milena-Blaser approved these changes

2022-12-12 19:25 UTC, blerinebee approved these changes

2022-12-12 19:27 UTC, nuweramohammad approved these changes

2022-12-12 19:44 UTC, merged